food_helper/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("recipes.urls")),
    path("", include("products.urls")),
    path("", include("user_ingredients.urls")),
    path("", include("recipe_ingredients.urls")),
    path("", include("ingredients.urls")),
]

ingredients/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .api.views import IngredientViewSet

router = SimpleRouter()
router.register("ingredients", IngredientViewSet)

urlpatterns = [path("api/", include(router.urls))]

products/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .api.views import ProductsViewSet
from .views import (
    ProductAddPageView,
    ProductDeleteView,
    ProductEditPageView,
    ProductHomePageView,
)

app_name = "products"

router = SimpleRouter()
router.register("products", ProductsViewSet)

urlpatterns = [
    path("product/", ProductHomePageView.as_view(), name="products-home-page"),
    path("product/add/", ProductAddPageView.as_view(), name="product-add"),
    path(
        "product/<int:product_id>/edit/",
        ProductEditPageView.as_view(),
        name="product-edit",
    ),
    path(
        "product/<int:pk>/delete/",
        ProductDeleteView.as_view(),
        name="product-delete",
    ),
    path("api/", include(router.urls)),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .api.views import APIRegisterView, MyObtainTokenPairView
from .views import (
    HomePageView,
    MyLoginView,
    MyResetPasswordView,
    ProfileView,
    RegisterView,
)

urlpatterns = [
    path("", HomePageView.as_view(), name="home-page"),
    path("register/", RegisterView.as_view(), name="register-page"),
    path(
        "login/",
        MyLoginView.as_view(template_name="users/login.html"),
        name="login-page",
    ),
    path("profile/", ProfileView.as_view(), name="profile-page"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout-page",
    ),
    path(
        "reset_password/",
        MyResetPasswordView.as_view(template_name="users/reset_password.html"),
        name="reset-password-page",
    ),
    path("api/auth/login/", MyObtainTokenPairView.as_view(), name="token-obtain-view"),
    path("api/auth/login/refresh/", TokenRefreshView.as_view(), name="token-refresh"),
    path("api/auth/register/", APIRegisterView.as_view(), name="auth-register"),
]

ingredients/models.py
from django.db import models

from products.models import Product


class Ingredient(models.Model):
    AMOUNT_TYPE_CHOICES = (
        ("kg", "kg"),
        ("g", "g"),
        ("l", "l"),
        ("ml", "ml"),
        ("szt.", "szt."),
        ("opak.", "opak."),
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity_type = models.CharField(
        max_length=5,
        choices=AMOUNT_TYPE_CHOICES,
    )

    class Meta:
        unique_together = ["product", "quantity_type"]

    def __str__(self):
        return f"{self.product.name}, {self.quantity_type}"

ingredients/forms.py
from django import forms

from products.models import Product

from .models import Ingredient


class IngredientForm(forms.ModelForm):
    product_name = forms.ModelChoiceField(queryset=Product.objects.all())

    class Meta:
        model = Ingredient
        fields = ["product_name", "quantity_type"]

ingredients/api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from ingredients.api.serializers import IngredientSerializer
from ingredients.models import Ingredient


class IngredientViewSet(viewsets.ModelViewSet):
    serializer_class = IngredientSerializer
    queryset = Ingredient.objects.all()
    permission_classes = [IsAuthenticated]

ingredients/templates/ingredients/ingredient_form.html
{% extends 'users/dashboard_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST">
    {% csrf_token %}
        <table class="table table-bordered" width="100%" cellspacing="0">
            <tbody>
                <tr>
                    <td>{{ form.amount|as_crispy_field }}</td>
                    <td>{{ ingredient_form.quantity_type|as_crispy_field }}</td>
                    <td>{{ ingredient_form.product_name|as_crispy_field }}</td>
                </tr>
            </tbody>
        </table>
    <div style="display: flex; justify-content: space-between;">
        {% if "Add" in title %}
            <button class="btn btn-outline-info" type="submit">Add</button>
        {% else %}
            <button class="btn btn-outline-info" type="submit">Save changes</button>
        {%  endif %}
        <a href="{% url 'products:product-add' %}" class="btn btn-outline-info" role="button">Add Product</a>
    </div>
    </form>
{% endblock %}