food_helper/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("recipes.urls")),
    path("", include("products.urls")),
    path("", include("user_ingredients.urls")),
    path("", include("recipe_ingredients.urls")),
    path("", include("ingredients.urls")),
]

recipe_ingredients/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .api.views import RecipeIngredientViewSet
from .views import (
    RecipeIngredientAddView,
    RecipeIngredientDeleteView,
    RecipeIngredientEditView,
)

app_name = "recipe_ingredients"

router = SimpleRouter()
router.register("recipe-ingredients", RecipeIngredientViewSet)

urlpatterns = [
    path(
        "recipe-ingredient/<int:recipe_id>/add-ingredient/",
        RecipeIngredientAddView.as_view(),
        name="ingredient-add",
    ),
    path(
        "recipe-ingredient/<int:recipe_id>/add-ingredient/<int:product_id>",
        RecipeIngredientAddView.as_view(),
        name="ingredient-add",
    ),
    path(
        "recipe-ingredient/<int:recipe_id>/edit-ingredient/<int:ingredient_id>/",
        RecipeIngredientEditView.as_view(),
        name="ingredient-edit",
    ),
    path(
        "recipe-ingredient/<int:recipe_id>/edit-ingredient/<int:ingredient_id>/<int:product_id>/",
        RecipeIngredientEditView.as_view(),
        name="ingredient-edit",
    ),
    path(
        "recipe-ingredient/<int:recipe_id>/delete-ingredient/<int:pk>/",
        RecipeIngredientDeleteView.as_view(),
        name="ingredient-delete",
    ),
    path("api/", include(router.urls)),
]

recipes/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .api.views import RecipeEditViewSet, RecipeViewSet
from .views import (
    RecipeAddPageView,
    RecipeDeleteView,
    RecipeEditPageView,
    RecipesHomePageView,
)

router = SimpleRouter()
router.register("recipes", RecipeViewSet)

urlpatterns = [
    path("recipes/", RecipesHomePageView.as_view(), name="recipes-home-page"),
    path("recipes/add/", RecipeAddPageView.as_view(), name="recipe-add"),
    path(
        "recipes/<int:pk>/edit/",
        RecipeEditPageView.as_view(),
        name="recipe-edit",
    ),
    path(
        "recipes/<int:pk>/delete/",
        RecipeDeleteView.as_view(),
        name="recipe-delete",
    ),
    path("api/", include(router.urls)),
    path(
        "api/recipes/<int:pk>/edit/",
        RecipeEditViewSet.as_view({"put": "update"}),
        name="recipe-edit",
    ),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .api.views import APIRegisterView, MyObtainTokenPairView
from .views import (
    HomePageView,
    MyLoginView,
    MyResetPasswordView,
    ProfileView,
    RegisterView,
)

urlpatterns = [
    path("", HomePageView.as_view(), name="home-page"),
    path("register/", RegisterView.as_view(), name="register-page"),
    path(
        "login/",
        MyLoginView.as_view(template_name="users/login.html"),
        name="login-page",
    ),
    path("profile/", ProfileView.as_view(), name="profile-page"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout-page",
    ),
    path(
        "reset_password/",
        MyResetPasswordView.as_view(template_name="users/reset_password.html"),
        name="reset-password-page",
    ),
    path("api/auth/login/", MyObtainTokenPairView.as_view(), name="token-obtain-view"),
    path("api/auth/login/refresh/", TokenRefreshView.as_view(), name="token-refresh"),
    path("api/auth/register/", APIRegisterView.as_view(), name="auth-register"),
]

recipes/models.py
# from django.contrib.postgres.fields import ArrayField
from django.db import models

from recipe_ingredients.models import RecipeIngredient
from users.models import Profile


class Recipe(models.Model):
    recipe_name = models.CharField(max_length=100, unique=True)
    preparation = models.TextField(blank=False, default="")
    recipe_ingredient = models.ManyToManyField(RecipeIngredient)
    # tags = ArrayField(models.CharField(max_length=20, null=True), blank=True, null=True)
    user = models.ForeignKey(
        Profile, on_delete=models.DO_NOTHING, null=True, blank=True
    )
    builtin = models.BooleanField(default=False)
    public = models.BooleanField(default=True)

recipes/forms.py
from django import forms

from .models import Recipe


class CreateNewRecipe(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["recipe_name", "preparation"]

    def __init__(self, *args, **kwargs):
        super(CreateNewRecipe, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "recipe_name":
                field.required = False


class EditRecipe(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["recipe_name", "preparation"]

    def __init__(self, *args, **kwargs):
        super(EditRecipe, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "recipe_name":
                field.required = False

recipes/api/views.py
from rest_framework import mixins, viewsets
from rest_framework.permissions import IsAuthenticated

from ..models import Recipe
from .serializers import RecipeEditSerializer, RecipeSerializer


class RecipeViewSet(
    viewsets.GenericViewSet,
    mixins.CreateModelMixin,
    mixins.DestroyModelMixin,
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin,
):
    serializer_class = RecipeSerializer
    queryset = Recipe.objects.all()
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class RecipeEditViewSet(viewsets.GenericViewSet, mixins.UpdateModelMixin):
    serializer_class = RecipeEditSerializer
    queryset = Recipe.objects.all()
    permission_classes = [IsAuthenticated]

recipes/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import CreateNewRecipe, EditRecipe
from .models import Recipe


class RecipesHomePageView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = "recipes/home.html"
    extra_context = {"title": "Recipes"}

    def get(self, request, *args, **kwargs):
        user_recipes = self.model.objects.filter(user=request.user.pk).order_by("id")
        recipes_with_ingredients = []
        for recipe in user_recipes:
            recipe_data = {
                "id": recipe.id,
                "recipe_name": recipe.recipe_name,
                "preparation": recipe.preparation,
                # "tags": recipe.tags,
                "ingredients": [],
            }

            ingredients = recipe.recipe_ingredient.all()

            for ingredient in ingredients:
                ingredient_data = {
                    "name": ingredient.ingredient.product.name,
                    "quantity": ingredient.amount,
                    "quantity_type": ingredient.ingredient.quantity_type,
                }
                recipe_data["ingredients"].append(ingredient_data)
            recipes_with_ingredients.append(recipe_data)
        context = self.extra_context
        context["recipes"] = recipes_with_ingredients
        return render(request, self.template_name, context)


class RecipeAddPageView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = CreateNewRecipe
    template_name = "recipes/recipe_form_new.html"
    extra_context = {"title": "Add Recipe"}

    def get(self, request, *args, **kwargs):
        context = self.extra_context
        context["form"] = self.form_class
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.instance.user = request.user.profile
            recipe = form.save()
            if "add_ingredient" in request.POST:
                return redirect("recipe_ingredients:ingredient-add", recipe.id)
            else:
                messages.success(request, "Recipe has been added")
                return redirect("recipes-home-page")
        else:
            messages.warning(request, "Invalid data in recipe")
            return redirect("recipe-add")


class RecipeEditPageView(LoginRequiredMixin, UpdateView):
    model = Recipe
    form_class = EditRecipe
    template_name = "recipes/recipe_form_edit.html"
    extra_context = {"title": "Edit Recipe"}

    def get(self, request, *args, **kwargs):
        recipe_id = self.get_object()
        recipe = get_object_or_404(self.model, pk=recipe_id.pk)
        context = self.extra_context
        context["form"] = self.form_class(
            initial={
                "recipe_name": recipe.recipe_name,
                "preparation": recipe.preparation,
                # "tags": recipe.tags,
                "recipe_id": recipe_id,
            }
        )
        context["ingredients"] = recipe.recipe_ingredient.all().order_by("id")
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        recipe_id = self.get_object()
        form = self.form_class(request.POST, instance=recipe_id)
        if form.is_valid():
            self.model.objects.filter(id=recipe_id.pk).update(
                recipe_name=form.cleaned_data.get("recipe_name"),
                preparation=form.cleaned_data.get("preparation"),
                # tags=form.cleaned_data.get("tags"),
            )
            if "add_ingredient" in request.POST:
                return redirect("recipe_ingredients:ingredient-add", recipe_id.pk)
            messages.success(request, "Recipe has been updated")
            return redirect("recipes-home-page")
        else:
            messages.warning(request, "Invalid data in recipe")
            return redirect("recipe-edit", recipe_id.pk)


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    success_url = reverse_lazy("recipes-home-page")

    def form_valid(self, form):
        messages.success(self.request, "Successfully remove recipe")
        return super().form_valid(form)

recipes/templates/recipes/home.html
{% extends 'users/dashboard_base.html' %}
{% block content %}
    <a href="{% url 'recipe-add' %}" class="btn btn-primary" role="button">Add</a>
{% if recipes %}
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellpadding="0">
                <thead>
                    <tr>
                        <td>Recipe name</td>
                        <td>Ingredients</td>
                        <td>Preparation</td>
{#                        <td>Tags</td>#}
                    </tr>
                </thead>
                <tbody>
                    {% for recipe in recipes %}
            <tr>
                <td>{{ recipe.recipe_name }}</td>
                <td>
                {% for ingredients in recipe.ingredients %}
                    <li>{{ ingredients.quantity }} {{ ingredients.quantity_type }} {{ ingredients.name }}</li>
                {% endfor %}
                </td>
                <td>{{ recipe.preparation }}</td>
{#                {% if recipe.tags %}#}
{#                    <td>{% for tag in recipe.tags %}{{ tag }}{% endfor %}</td>#}
{#                {% else %}#}
{#                    <td></td>#}
{#                {% endif %}#}
                <td><a href="{% url 'recipe-edit' recipe.id %}" class="btn btn-primary" role="button">Edit</a></td>
                <td>
                    <form method="post" action="{% url 'recipe-delete' recipe.id %}">
                        {% csrf_token %}
                     <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete recipe?')" value="Delete">
                    </form>
                </td>
            </tr>
        </tbody>
        {% endfor %}

            </table>
        </div>
    </div>
{% else %}
    <p>Add recipe</p>
{% endif %}

{% endblock %}

recipes/templates/recipes/recipe_form.html
{% extends 'users/dashboard_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form.recipe_name|as_crispy_field }}
                Ingredients
                <div>
                    <button class="btn btn-primary" type="submit" name="add_ingredient">Add ingredient</button>
                </div>
                {% if ingredients.count > 0 %}
                    <table id="ingredient-table" class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <td>Amount</td>
                            <td>Quantity type</td>
                            <td>Product</td>
                            <td></td>
                        </tr>
                    </thead>

                    <tbody>
                    <tr style="display: none">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><form></form></td>
                    </tr>
                    {% for ingredient in ingredients %}
                        <tr>
                            <td>{{ ingredient.amount }}</td>
                            <td>{{ ingredient.ingredient.quantity_type }}</td>
                            <td>{{ ingredient.ingredient.product.name }}</td>
                            <td><a href="{% url 'recipe_ingredients:ingredient-edit' form.initial.recipe_id ingredient.id %}" class="btn btn-primary" role="button">Edit</a></td>
                            <td>
                                <form method="post" action="{% url 'recipe_ingredients:ingredient-delete' form.initial.recipe_id ingredient.id %}">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete ingredient?')" value="Delete">
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                {% endif %}
                {{ form.preparation|as_crispy_field }}
{#                {{ form.tags|as_crispy_field }}#}
            <div class="form-group">
                {% if "Add" in title %}
                <button class="btn btn-outline-info" type="submit">Add</button>
                {% else %}
                <button class="btn btn-outline-info" type="submit">Save changes</button>
                {% endif %}
            </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

recipes/templates/recipes/recipe_form_edit.html
{% extends 'users/dashboard_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form.recipe_name|as_crispy_field }}
                Ingredients
                <div>
                    <button class="btn btn-primary" type="submit" name="add_ingredient">Add ingredient</button>
                </div>
                {% if ingredients.count > 0 %}
                    <table id="ingredient-table" class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <td>Amount</td>
                            <td>Quantity type</td>
                            <td>Product</td>
                            <td></td>
                        </tr>
                    </thead>

                    <tbody>
                    <tr style="display: none">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><form></form></td>
                    </tr>
                    {% for ingredient in ingredients %}
                        <tr>
                            <td>{{ ingredient.amount }}</td>
                            <td>{{ ingredient.ingredient.quantity_type }}</td>
                            <td>{{ ingredient.ingredient.product.name }}</td>
                            <td><a href="{% url 'recipe_ingredients:ingredient-edit' form.initial.recipe_id.pk ingredient.id %}" class="btn btn-primary" role="button">Edit</a></td>
                            <td>
                                <form method="post" action="{% url 'recipe_ingredients:ingredient-delete' form.initial.recipe_id.pk ingredient.id %}">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete ingredient?')" value="Delete">
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                {% endif %}
                {{ form.preparation|as_crispy_field }}
{#                {{ form.tags|as_crispy_field }}#}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Save changes</button>
            </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

recipes/templates/recipes/recipe_form_new.html
{% extends 'users/dashboard_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form.recipe_name|as_crispy_field }}
                Ingredients
                <div>
                    <button class="btn btn-primary" type="submit" name="add_ingredient">Add ingredient</button>
                </div>
                {% if ingredients.count > 0 %}
                    <table id="ingredient-table" class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <td>Amount</td>
                            <td>Quantity type</td>
                            <td>Product</td>
                            <td></td>
                        </tr>
                    </thead>

                    <tbody>
                    <tr style="display: none">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><form></form></td>
                    </tr>
                    {% for ingredient in ingredients %}
                        <tr>
                            <td>{{ ingredient.amount }}</td>
                            <td>{{ ingredient.ingredient.quantity_type }}</td>
                            <td>{{ ingredient.ingredient.product.name }}</td>
                            <td><a href="{% url 'recipe_ingredients:ingredient-edit' form.initial.recipe_id ingredient.id %}" class="btn btn-primary" role="button">Edit</a></td>
                            <td>
                                <form method="post" action="{% url 'recipe_ingredients:ingredient-delete' form.initial.recipe_id ingredient.id %}">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete ingredient?')" value="Delete">
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                {% endif %}
                {{ form.preparation|as_crispy_field }}
{#                {{ form.tags|as_crispy_field }}#}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Add</button>
            </div>
            </fieldset>
        </form>
    </div>
{% endblock %}