food_helper/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("recipes.urls")),
    path("", include("products.urls")),
    path("", include("user_ingredients.urls")),
    path("", include("recipe_ingredients.urls")),
    path("", include("ingredients.urls")),
]

products/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .api.views import ProductsViewSet
from .views import (
    ProductAddPageView,
    ProductDeleteView,
    ProductEditPageView,
    ProductHomePageView,
)

app_name = "products"

router = SimpleRouter()
router.register("products", ProductsViewSet)

urlpatterns = [
    path("product/", ProductHomePageView.as_view(), name="products-home-page"),
    path("product/add/", ProductAddPageView.as_view(), name="product-add"),
    path(
        "product/<int:product_id>/edit/",
        ProductEditPageView.as_view(),
        name="product-edit",
    ),
    path(
        "product/<int:pk>/delete/",
        ProductDeleteView.as_view(),
        name="product-delete",
    ),
    path("api/", include(router.urls)),
]

user_ingredients/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .api.views import UserIngredientViewSet
from .views import (
    UserIngredientsAddPageView,
    UserIngredientsDeletePageView,
    UserIngredientsEditPageView,
    UserIngredientsHomePageView,
)

app_name = "my_ingredients"

router = SimpleRouter()
router.register("user-ingredients", UserIngredientViewSet)

urlpatterns = [
    path(
        "my-ingredients/",
        UserIngredientsHomePageView.as_view(),
        name="useringredients-home-page",
    ),
    path(
        "my-ingredients/add/",
        UserIngredientsAddPageView.as_view(),
        name="useringredient-add",
    ),
    path(
        "my-ingredients/add/<int:product_id>",
        UserIngredientsAddPageView.as_view(),
        name="useringredient-add",
    ),
    path(
        "my-ingredients/<int:my_ingredient_id>/edit/",
        UserIngredientsEditPageView.as_view(),
        name="useringredient-edit",
    ),
    path(
        "my-ingredients/<int:my_ingredient_id>/edit/<int:product_id>",
        UserIngredientsEditPageView.as_view(),
        name="useringredient-edit",
    ),
    path(
        "my-ingredients/<int:pk>/delete/",
        UserIngredientsDeletePageView.as_view(),
        name="useringredient-delete",
    ),
    path("api/", include(router.urls)),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .api.views import APIRegisterView, MyObtainTokenPairView
from .views import (
    HomePageView,
    MyLoginView,
    MyResetPasswordView,
    ProfileView,
    RegisterView,
)

urlpatterns = [
    path("", HomePageView.as_view(), name="home-page"),
    path("register/", RegisterView.as_view(), name="register-page"),
    path(
        "login/",
        MyLoginView.as_view(template_name="users/login.html"),
        name="login-page",
    ),
    path("profile/", ProfileView.as_view(), name="profile-page"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout-page",
    ),
    path(
        "reset_password/",
        MyResetPasswordView.as_view(template_name="users/reset_password.html"),
        name="reset-password-page",
    ),
    path("api/auth/login/", MyObtainTokenPairView.as_view(), name="token-obtain-view"),
    path("api/auth/login/refresh/", TokenRefreshView.as_view(), name="token-refresh"),
    path("api/auth/register/", APIRegisterView.as_view(), name="auth-register"),
]

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm, User, UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class MyResetPasswordForm(PasswordResetForm):
    new_password = forms.CharField(widget=forms.PasswordInput())
    confirm_new_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ["email"]

users/api/views.py
from django.contrib.auth.models import User
from rest_framework import generics
from rest_framework.permissions import AllowAny
from rest_framework_simplejwt.views import TokenObtainPairView

from .serializers import MyTokenObtainPairSerializer, RegisterSerializer


class MyObtainTokenPairView(TokenObtainPairView):
    permission_classes = (AllowAny,)
    serializer_class = MyTokenObtainPairSerializer


class APIRegisterView(generics.CreateAPIView):
    queryset = User.objects.all()
    permission_classes = (AllowAny,)
    serializer_class = RegisterSerializer

users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import AuthenticationForm, LoginView, PasswordResetView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View

from .forms import MyResetPasswordForm, UserRegisterForm


class CustomAuthForm(AuthenticationForm):
    error_messages = {"invalid_login": "Wrong username or password"}


class MyResetPasswordView(PasswordResetView):
    form_class = MyResetPasswordForm
    success_url = reverse_lazy("login-page")

    def form_valid(self, form):
        email = form.data.get("email")
        new_password = form.data.get("new_password")
        confirm_new_password = form.data.get("confirm_new_password")

        try:
            user = get_user_model().objects.get(email=email)
        except get_user_model().DoesNotExist:
            messages.warning(self.request, "Email does not exist")
            return redirect("reset-password-page")

        if new_password == confirm_new_password:
            user.set_password(new_password)
            user.save()
            messages.success(self.request, "Password successfully reset")
            return redirect("login-page")
        else:
            messages.error(self.request, "Passwords are not the same")
            return redirect("reset-password-page")

    def form_invalid(self, form):
        messages.error(self.request, "Invalid data in reset password form")
        return super().form_invalid(form)


class MyLoginView(LoginView):
    redirect_authenticated_user = True
    form_class = CustomAuthForm
    success_url = reverse_lazy("users/home.html")


class HomePageView(View):
    template_name = "users/home.html"
    context = {"title": "Home Page"}

    def get(self, request):
        if request.user.is_authenticated:
            user_ingredients = request.user.profile.useringredient_set.all()
            user_recipes = request.user.profile.recipe_set.all()
            ready_recipes, sorted_keys = self.ready_recipes(
                user_recipes, user_ingredients
            )
            self.context["ready_recipes"] = ready_recipes
            self.context["sorted_keys"] = sorted_keys
            self.template_name = "users/dashboard.html"
            return render(request, self.template_name, self.context)
        else:
            return render(request, self.template_name, self.context)

    def ready_recipes(self, user_recipes, user_ingredients):
        result_recipes = {}

        for recipe in user_recipes:
            ingredients = recipe.recipe_ingredient.all()
            if len(ingredients) == 0:
                continue
            missing_ingredients_counter = 0
            for ingredient_item in ingredients:
                ingredient_name = ingredient_item.ingredient.product.name
                ingredient_quantity = ingredient_item.amount
                ingredient_quantity_type = ingredient_item.ingredient.quantity_type
                ingredient_found = False
                for user_ingredient_item in user_ingredients:
                    if (
                        ingredient_name == user_ingredient_item.ingredient.product.name
                        and ingredient_quantity <= user_ingredient_item.amount
                        and ingredient_quantity_type
                        == user_ingredient_item.ingredient.quantity_type
                    ):
                        ingredient_found = True
                        break
                if not ingredient_found:
                    missing_ingredients_counter += 1
            if str(missing_ingredients_counter) in result_recipes:
                result_recipes[str(missing_ingredients_counter)].append(recipe)
            else:
                result_recipes[str(missing_ingredients_counter)] = [recipe]
        sorted_keys = sorted(result_recipes.keys())
        return result_recipes, sorted_keys


class RegisterView(View):
    template_name = "users/register.html"
    form = UserRegisterForm()
    context = {"title": "Register", "form": form}

    def get(self, request):
        return render(request, self.template_name, self.context)

    @staticmethod
    def post(request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            email_in_db = User.objects.filter(email=form.data.get("email"))
            if not email_in_db:
                form.save()
                messages.success(request, "User created correctly")
                return redirect("login-page")
        messages.warning(request, "Form have invalid data")
        return redirect("register-page")


class ProfileView(View):
    template_name = "users/profile.html"
    context = {"title": "Profile"}

    @method_decorator(login_required)
    def get(self, request):
        return render(request, self.template_name, self.context)

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">

    <link rel="stylesheet" type="text/css" href="{% static 'users/base.css' %}" />

    {% if title %}
        <title>Food Helper - {{ title }}</title>
    {% else %}
        <title>Food Helper</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'home-page' %}">Food Helper</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <!-- Navbar Left Side -->
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'home-page' %}">Home</a>
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'recipes-home-page' %}">Przepisy</a>
                            <a class="nav-item nav-link" href="{% url 'fridges-home-page' %}">Lodówka</a>
                        {% endif %}
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'profile-page' %}">Profile</a>
                            <a class="nav-item nav-link" href="{% url 'logout-page' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'login-page' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'register-page' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                        <div class = "alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/dashboard.html
{% extends 'users/dashboard_base.html' %}
{% load custom_filters %}
{% block content %}
    {% if user.is_authenticated %}

    {% for key in sorted_keys %}
    <div class="card shadow mb-4">
    {% if key == '0' %}
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Recipes, which can be done</h6>
        </div>
    {% else %}
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Missing ingredients in recipes: {{ key }}</h6>
        </div>
    {% endif %}
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Recipe Name</th>
                        <th>Ingredients</th>
                        <th>Preparation</th>
{#                        <th>Tags</th>#}
                    </tr>
                </thead>
                <tbody>
                    {% for recipe in ready_recipes|get_item:key %}
            <tr>
                <td>{{ recipe.recipe_name }}</td>
                <td>
                {% for ingredients in recipe.recipe_ingredient.all %}
                    <li>{{ ingredients.amount }} {{ ingredients.ingredient.quantity_type }} {{ ingredients.ingredient.product.name }}</li>
                {% endfor %}
                </td>
                <td>{{ recipe.preparation }}</td>
{#                {% if recipe.tags %}#}
{#                    <td>{% for tag in recipe.tags %}{{ tag }}{% endfor %}</td>#}
{#                {% else %}#}
{#                    <td></td>#}
{#                {% endif %}#}
            </tr>
        {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
        {% endfor %}
{% endif %}
{% endblock %}

users/templates/users/dashboard_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{{ title }}</title>

        <!-- Custom fonts for this template-->
        <link href="{% static "users/all.min.css" %}" rel="stylesheet" type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="{% static 'users/sb-admin-2.min.css' %}" rel="stylesheet">
    </head>
    <body id="page-top">
        <!-- Page Wrapper -->
        <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'home-page' %}">
                <div class="sidebar-brand-text mx-3">Food Helper</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home-page' %}">
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'recipes-home-page' %}">
                    <span>Recipes</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'products:products-home-page' %}">
                    <span>Products</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'my_ingredients:useringredients-home-page' %}">
                    <span>My Ingredients</span>
                </a>
            </li>

        </ul>
        <!-- End of Sidebar -->

    <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{% url 'profile-page' %}">
                                    Profile
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout-page' %}">
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                        <div class = "alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </main>

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
                    </div>
                    {% block content %}{% endblock %}
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Food Helper <script>document.write(new Date().getFullYear())</script></span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->
    </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="../../static/js/jquery.min.js"></script>
    <script src="../../static/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="../../static/js/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="../../static/js/sb-admin-2.min.js"></script>
    </body>
</html>

users/templates/users/home.html
{% extends 'users/base.html' %}
{% load custom_filters %}
{% block content %}
{% if user.is_authenticated %}
    <table>
    <tbody>
    {% for key in sorted_keys %}
        {% if key == '0' %}
            <tr>
                <td colspan="4">Przepisy, które można zrobić</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Brakujące składniki w przepisach: {{ key }}</td>
            </tr>
        {% endif %}
        <tr>
            <td>Nazwa</td>
            <td>Składniki</td>
            <td>Przygotowanie</td>
            <td>Tagi</td>
        </tr>
        {% for recipe in ready_recipes|get_item:key %}
            <tr>
                <td>{{ recipe.recipe_name }}</td>
                <td>
                {% for ingredients in recipe.ingredients.all %}
                    <li>{{ ingredients.quantity }} {{ ingredients.quantity_type }} {{ ingredients.name }}</li>
                {% endfor %}
                </td>
                <td>{{ recipe.preparation }}</td>
                {% if recipe.tags %}
                    <td>{% for tag in recipe.tags %}{{ tag }}{% endfor %}</td>
                {% else %}
                    <td></td>
                {% endif %}
            </tr>
            <tr>
                <td colspan="4"></td>
            </tr>
        {% endfor %}
    {% endfor %}
    </tbody>
    </table>
{% endif %}
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Forget password? <a class="ml-2" href="{% url 'reset-password-page' %}">Reset password</a>
            </small>
            <br/>
            <small class="text-muted">
                Does not have an account? <a class="ml-2" href="{% url 'register-page' %}">Sign Up</a>
            </small>
        </div>
    </div>
{% endblock %}

users/templates/users/logout.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <h2>You have been log out</h2>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/dashboard_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <p>Hi, {{user.username}}! You're logged in :)</p>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register form</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Have an account? <a class="ml-2" href="{% url 'login-page' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset password!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Have an account? <a class="ml-2" href="{% url 'login-page' %}">Sign In</a>
            </small>
            <br/>
            <small class="text-muted">
                Does not have an account? <a class="ml-2" href="{% url 'register-page' %}">Sign Up</a>
            </small>
        </div>
    </div>
{% endblock %}